version: '3'


services:
  apple_ble:
    container_name: apple_ble
    image: ubuntu
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    stdin_open: true
    network_mode: "host"
    privileged: true
    devices:
      - '/dev:/dev'
